title="TeXaDemic"
description = "TeXaDemic - A LaTeX-style hugo theme with the gruvbox color scheme for personal and group academics sites"
footnote = """
Powered by  <a class=link href=https://gohugo.io target=_blank rel=noopener>Hugo</a> | 
Theme <a class=link href=https://github.com/walkloud/hugo-texademic target=_blank rel=noopener>TeXaDemic</a>
"""
keywords = ["hugo", "latex", "theme", "academic", "texify", "texify2", "texify3", "texademic"]
customCSS = []
customJS = []
dateFormat = "2 January 2006"
emphasisWithDots = true
since = "2025"
toc = true
showWordCount = true
showReadingTime = true
rootFontSize = "100%"
math = true
enableDuckDuckGoSearchBox = true
numberedSubtitles = true
enableInlineShortcodes = true

[buymeacoffee]
code = """
<script data-name="BMC-Widget" 
    data-cfasync="true" 
    src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js" 
    data-id="loudwalker" 
    data-description="Like what I do? Buy me a coffee!" 
    data-message="" 
    data-color="#d79921" 
    data-position="Right" 
    data-x_margin="18" 
    data-y_margin="18"
    crossorigin="anonymous">
</script>
"""

[sharingbuttons]
facebook = true
x = true
email = true
linkedin = true
reddit = true
whatsapp = true
hackernews = true
telegram = true
